# install the stable release of the Chef Development Kit (ChefDK)
# use chef-current-precise to install the pre-release
addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chefdk
    code_climate:
        repo_token: abe55c34d937fb17eaa7d459e20ad0e1359108d704eef0490a55c471c2bafb88

services: docker

# https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
install: true

before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)" # make ChefDK's Ruby the default
  - chef --version
  - chef exec berks install

script:
 - chef exec rake default
